/**
 * DOCUMENT GENERATION
 *
 * Four outputs, all of which the citizen files themselves:
 *   1. the submission packet — cover sheet, enclosure order, counter checklist
 *   2. the readiness report — every check, with its evidence
 *   3. an escalation letter — first appeal, second appeal, or RTI
 *
 * Everything is generated in English. That is deliberate rather than lazy: the
 * office record and the officer's file are in English or Kannada, and a letter
 * the receiving clerk cannot process helps nobody. The app explains every line
 * of these documents in the citizen's own language on screen and aloud; the
 * paper that goes across the counter is in the language the counter uses.
 *
 * Nothing here is submitted anywhere. Every file downloads to the citizen.
 */

import PDFDocument from 'pdfkit';
import { formatDate } from './engine/clock.js';

const INK = '#12211f';
const MUTED = '#6a7a75';
const ACCENT = '#0f4c43';
const RULE = '#d7d3c7';

function startDoc(res, filename) {
  const doc = new PDFDocument({
    margin: 54,
    size: 'A4',
    // Compression off makes the content stream plain text, so CI can assert on
    // the words and dates that actually appear in a generated appeal rather
    // than only on the byte count. Off in tests, on everywhere else.
    compress: process.env.PDF_NO_COMPRESS !== '1',
    info: { Title: filename, Producer: 'Seedha Kaam (prototype)' }
  });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Cache-Control', 'no-store');
  doc.pipe(res);
  return doc;
}

function letterhead(doc, title, subtitle) {
  doc.fillColor(ACCENT).font('Helvetica-Bold').fontSize(9).text('SEEDHA KAAM · CITIZEN-PREPARED DOCUMENT · PROTOTYPE', { characterSpacing: 1.2 });
  doc.moveDown(0.8);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(19).text(title);
  if (subtitle) doc.moveDown(0.2).fillColor(MUTED).font('Helvetica').fontSize(10).text(subtitle);
  doc.moveDown(0.7);
  hr(doc);
  doc.moveDown(0.7);
}

function hr(doc) {
  const y = doc.y;
  doc.save().strokeColor(RULE).lineWidth(1).moveTo(doc.page.margins.left, y).lineTo(doc.page.width - doc.page.margins.right, y).stroke().restore();
}

function section(doc, heading) {
  if (doc.y > doc.page.height - 140) doc.addPage();
  doc.moveDown(0.9).fillColor(ACCENT).font('Helvetica-Bold').fontSize(11).text(heading.toUpperCase(), { characterSpacing: 0.8 });
  doc.moveDown(0.4).fillColor(INK).font('Helvetica').fontSize(10.5);
}

function kv(doc, label, value) {
  doc.font('Helvetica-Bold').fontSize(9.5).fillColor(MUTED).text(label.toUpperCase(), { continued: false, characterSpacing: 0.5 });
  doc.font('Helvetica').fontSize(11).fillColor(INK).text(value == null || value === '' ? '—' : String(value));
  doc.moveDown(0.45);
}

function footer(doc, extra) {
  doc.moveDown(1.2);
  hr(doc);
  doc.moveDown(0.5).fillColor(MUTED).font('Helvetica').fontSize(7.8)
    .text(extra || 'Generated by Seedha Kaam, an independent prototype. Not a government form and not affiliated with any government body. No government system was accessed to produce this document, and nothing here has been submitted on your behalf. Verify every requirement against the current official notification before relying on it.', { align: 'left' });
}

/* ------------------------------------------------------------------ *
 * 1. Submission packet
 * ------------------------------------------------------------------ */

export function streamPacket(res, { caseData, evaluation, jurisdiction, language = 'en' }) {
  const doc = startDoc(res, 'seedha-kaam-submission-packet.pdf');
  const office = jurisdiction?.candidates?.[0];
  const applicant = caseData.applicant?.name || 'Applicant';

  letterhead(doc, 'Khata transfer — submission packet', `Prepared ${formatDate(new Date(), 'en')} for ${applicant}`);

  section(doc, 'Where to take this');
  kv(doc, 'Corporation', office?.corporation || 'Not yet resolved');
  kv(doc, 'Zone / sub-division', office?.zone || '—');
  kv(doc, 'Counter', office?.office || '—');
  kv(doc, 'Property address', caseData.address || '—');
  if (jurisdiction?.confidence === 'contested') {
    doc.fillColor('#8a5a12').font('Helvetica-Bold').fontSize(10)
      .text('This address is close to a corporation boundary. Call this office and quote your property ID before travelling. If the record is not with them, the alternate office is listed at the end of this packet.');
    doc.moveDown(0.4).fillColor(INK).font('Helvetica').fontSize(10.5);
  }

  section(doc, 'Enclosures — assemble in this order');
  const order = [
    'Signed transfer application (top sheet)',
    ...(evaluation?.documents?.supplied || []).map((d) => d.label || d.kind)
  ];
  order.forEach((item, index) => {
    doc.font('Helvetica').fontSize(10.5).fillColor(INK).text(`${String(index + 1).padStart(2, '0')}.  ${item}`);
    doc.moveDown(0.15);
  });

  section(doc, 'Pre-flight result');
  kv(doc, 'Blocking issues outstanding', String(evaluation?.counts?.blocks ?? '—'));
  kv(doc, 'Issues that may cause an objection', String(evaluation?.counts?.delays ?? '—'));
  kv(doc, 'Rules applied to this case', `${evaluation?.scoreBasis?.rulesApplied ?? '—'} of ${(evaluation?.scoreBasis?.rulesApplied || 0) + (evaluation?.scoreBasis?.rulesSkipped || 0)} in rule pack ${evaluation?.rulePack || '—'}`);

  if (evaluation?.findings?.length) {
    section(doc, 'Every check that produced a finding');
    for (const finding of evaluation.findings) {
      if (doc.y > doc.page.height - 160) doc.addPage();
      doc.font('Helvetica-Bold').fontSize(10.5).fillColor(finding.severity === 'blocks' ? '#9a3412' : finding.severity === 'delays' ? '#8a5a12' : MUTED)
        .text(`${finding.code} · ${finding.severity.toUpperCase()} · ${finding.title}`);
      doc.font('Helvetica').fontSize(9.6).fillColor(INK).text(finding.why);
      doc.font('Helvetica-Oblique').fontSize(9).fillColor(MUTED)
        .text(`Evidence — rule ${finding.ruleId}: ${finding.evidence?.comparison || finding.evidence?.note || '—'}`);
      doc.moveDown(0.55);
    }
  }

  section(doc, 'At the counter');
  [
    'Hand over the packet in the order above. Do not let the enclosures be reshuffled.',
    'Ask for an acknowledgement number and make sure it is written on your copy. Without it you have no clock.',
    'Ask for the name of the service and the stipulated number of days. It is printed on the acknowledgement slip.',
    'If you are told the papers are not in order, ask which document and which field. This packet lists every check that was run and what it found.',
    'You are not required to pay anyone anything beyond the notified fee, and the notified fee has a receipt.'
  ].forEach((line) => { doc.font('Helvetica').fontSize(10.5).fillColor(INK).text(`•  ${line}`); doc.moveDown(0.25); });

  if (jurisdiction?.candidates?.length > 1) {
    section(doc, 'Alternate office (boundary case)');
    const alt = jurisdiction.candidates[1];
    kv(doc, 'Corporation', alt.corporation);
    kv(doc, 'Zone / sub-division', alt.zone);
    kv(doc, 'Counter', alt.office);
  }

  footer(doc, 'Generated by Seedha Kaam, an independent prototype. In this demonstration deployment all property records are synthetic. This packet has not been submitted to any office — you file it yourself. Not a government form; not affiliated with any government body.');
  doc.end();
}

/* ------------------------------------------------------------------ *
 * 2. Readiness report
 * ------------------------------------------------------------------ */

export function streamReport(res, { caseData, evaluation }) {
  const doc = startDoc(res, 'seedha-kaam-readiness-report.pdf');
  letterhead(doc, 'Document readiness report', `${caseData.applicant?.name || 'Applicant'} · rule pack ${evaluation.rulePack} · ${formatDate(new Date(), 'en')}`);

  section(doc, 'Verdict');
  const verdictText = {
    'will-be-refused': 'As things stand, this application would be refused at the counter.',
    'may-be-objected': 'This application would probably be accepted, then come back as an objection.',
    ready: 'Every applicable check passed. This application is ready to file.'
  }[evaluation.verdict];
  doc.font('Helvetica-Bold').fontSize(13).fillColor(INK).text(verdictText);
  doc.moveDown(0.5).font('Helvetica').fontSize(10).fillColor(MUTED)
    .text(`${evaluation.counts.blocks} blocking · ${evaluation.counts.delays} likely objection · ${evaluation.counts.advisory} worth knowing. Readiness ${evaluation.score}%, computed as a severity-weighted pass rate over the ${evaluation.scoreBasis.rulesApplied} rules that applied to this case.`);

  section(doc, 'Findings, with evidence');
  for (const finding of evaluation.findings) {
    if (doc.y > doc.page.height - 200) doc.addPage();
    doc.font('Helvetica-Bold').fontSize(11).fillColor(INK).text(`${finding.code} — ${finding.title}`);
    doc.font('Helvetica').fontSize(9.5).fillColor(MUTED).text(`${finding.severity} · fix typically takes ${finding.expectedDays} day(s) · ${finding.owner}`);
    doc.moveDown(0.3).font('Helvetica').fontSize(10.5).fillColor(INK).text(finding.why);
    doc.moveDown(0.25).font('Helvetica-Bold').fontSize(10).fillColor(INK).text('What to do: ', { continued: true }).font('Helvetica').text(finding.fix);
    doc.moveDown(0.25).font('Helvetica-Oblique').fontSize(9).fillColor(MUTED)
      .text(`Why this answer — rule ${finding.ruleId}: ${finding.evidence?.note || ''} ${finding.evidence?.comparison || ''}`);
    if (finding.citation) {
      doc.font('Helvetica-Oblique').fontSize(8.5).fillColor(MUTED)
        .text(`Source: ${finding.citation.source} (last verified ${finding.citation.lastVerified}${finding.citation.verified ? '' : ' — NOT traced to a published clause'})`);
    }
    doc.moveDown(0.8);
  }

  section(doc, 'How this verdict was reached');
  doc.font('Helvetica').fontSize(10).fillColor(INK).text(
    `A deterministic rule engine evaluated rule pack ${evaluation.rulePack} against the fields in your documents. ${evaluation.scoreBasis.rulesApplied} rules applied to this case and ${evaluation.scoreBasis.rulesSkipped} did not (a purchase is not checked for a death certificate, for example). No language model took part in any verdict on this page. A model may have read text off a photograph, but every value it read was shown to you for confirmation before any rule ran.`
  );

  footer(doc);
  doc.end();
}

/* ------------------------------------------------------------------ *
 * 3. Escalation letters
 * ------------------------------------------------------------------ */

const BODY = {
  'first-appeal': (facts, applicant) => [
    `I applied for ${facts.serviceName} on ${formatDate(facts.submittedAt, 'en')}. The application was received under acknowledgement number ${facts.acknowledgementNumber}.`,
    `The stipulated period for this service is ${facts.slaDays} calendar days, which expired on ${formatDate(facts.deadlineAt, 'en')}. As of today, ${formatDate(facts.today, 'en')}, ${facts.elapsedDays} days have elapsed since submission and the application is ${facts.daysOverdue} days beyond the stipulated period. No disposal has been communicated to me.`,
    `I therefore request that this appeal be registered and the application disposed of. I am informed that this appeal is to be disposed of within ${facts.disposalDays} days, that is by ${formatDate(facts.replyDueBy, 'en')}.`,
    'I request a written communication of the outcome, and if the application is to be rejected, the specific ground and the document or field relied upon.'
  ],
  'second-appeal': (facts) => [
    `I applied for ${facts.serviceName} on ${formatDate(facts.submittedAt, 'en')} under acknowledgement number ${facts.acknowledgementNumber}. The stipulated period of ${facts.slaDays} days expired on ${formatDate(facts.deadlineAt, 'en')}.`,
    `A first appeal was preferred after that date. The application remains undisposed ${facts.daysOverdue} days beyond the stipulated period, and the period allowed for disposal of the first appeal has also passed.`,
    `I therefore prefer this second appeal and request disposal within ${facts.disposalDays} days, that is by ${formatDate(facts.replyDueBy, 'en')}.`,
    'I request that the outcome, and the reason for the delay, be communicated to me in writing.'
  ],
  rti: (facts) => [
    'Under the Right to Information Act 2005, I request the following information in respect of the application described below.',
    `Application: ${facts.serviceName}. Acknowledgement number: ${facts.acknowledgementNumber}. Date of submission: ${formatDate(facts.submittedAt, 'en')}.`,
    'Information sought:',
    '  (a) the current status of the application;',
    '  (b) the file movement history, showing the date the file was received by each officer and the date it left them;',
    '  (c) the name of the designation (not the individual) currently holding the file;',
    '  (d) if the application has been rejected or returned, a copy of the order or endorsement and the ground recorded;',
    '  (e) the stipulated period notified for this service and the reason recorded, if any, for exceeding it.',
    `I am a citizen of India. The prescribed fee is enclosed / will be paid as directed. I request a reply within the ${facts.disposalDays} days allowed by the Act.`
  ]
};

const TITLES = {
  'first-appeal': 'First appeal — delay in a time-bound service',
  'second-appeal': 'Second appeal — continued delay in a time-bound service',
  rti: 'Application under the Right to Information Act, 2005'
};

export function streamEscalation(res, { facts, caseData }) {
  const applicant = caseData.applicant?.name || 'Applicant';
  const doc = startDoc(res, `seedha-kaam-${facts.rung.id}.pdf`);

  letterhead(doc, TITLES[facts.rung.id], `Draft prepared for ${applicant} to review, sign and file`);

  doc.font('Helvetica').fontSize(11).fillColor(INK);
  doc.text('To,');
  doc.font('Helvetica-Bold').text(facts.addressedToRole);
  doc.font('Helvetica').text(facts.office?.office || 'The office where the application was submitted');
  if (facts.office?.corporation) doc.text(facts.office.corporation);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('Subject: ', { continued: true }).font('Helvetica')
    .text(`${TITLES[facts.rung.id]} — acknowledgement ${facts.acknowledgementNumber}`);
  doc.moveDown(0.9);
  doc.text('Sir / Madam,');
  doc.moveDown(0.6);

  for (const paragraph of BODY[facts.rung.id](facts, applicant)) {
    doc.font('Helvetica').fontSize(11).fillColor(INK).text(paragraph, { align: 'left', lineGap: 2 });
    doc.moveDown(0.55);
  }

  doc.moveDown(0.6).text('Yours faithfully,');
  doc.moveDown(2.2);
  doc.font('Helvetica-Bold').text(applicant);
  doc.font('Helvetica').fontSize(10).fillColor(MUTED).text('Signature: ______________________     Date: ______________');
  doc.moveDown(0.4).text('Address and contact number to be filled in by hand before filing.');

  section(doc, 'The arithmetic behind this letter');
  doc.font('Helvetica').fontSize(9.6).fillColor(INK);
  [
    ['Submitted', formatDate(facts.submittedAt, 'en')],
    ['Stipulated period', `${facts.slaDays} calendar days`],
    ['Deadline', formatDate(facts.deadlineAt, 'en')],
    ['Today', formatDate(facts.today, 'en')],
    ['Days elapsed', String(facts.elapsedDays)],
    ['Days beyond the period', String(facts.daysOverdue)],
    ['Reply due by', formatDate(facts.replyDueBy, 'en')],
    ['Basis', facts.basis]
  ].forEach(([k, v]) => { doc.font('Helvetica-Bold').text(`${k}: `, { continued: true }).font('Helvetica').text(v); });

  footer(doc, 'Drafted by Seedha Kaam for you to review, sign and file yourself. It has NOT been sent to anybody. Seedha Kaam is an independent prototype, is not affiliated with any government body, and does not name or accuse any individual officer. Check the correct addressee and the current procedure before filing — the role named above is encoded from the published framework and may have changed.');
  doc.end();
}
